tarefas/urls.py
from django.urls import path
from . import views


app_name = 'tarefas'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:tarefa_id>', views.detalhe, name="detalhe"),
    path('apagar/<int:tarefa_id>', views.apagar, name="apagar"),
]

webdev/urls.py
from django.contrib import admin
from django.urls import path, include
from . import home_view

urlpatterns = [
    path('', home_view.home),
    path('admin/', admin.site.urls),
    path('tarefas/', include('tarefas.urls'))
]

tarefas/models.py
from django.db import models

# Create your models here.
class Tarefa(models.Model):
    nome = models.CharField(max_length=128)
    feita = models.BooleanField(default=False)
    

tarefas/forms.py
from django.forms import ModelForm
from tarefas.models import Tarefa


class TarefaNovaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome']


class TarefaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome', 'feita']

tarefas/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from tarefas.forms import TarefaNovaForm, TarefaForm
from django.urls import reverse
from tarefas.models import Tarefa



# Create your views here.
def index(request):
    # Verificando o metodo
    if request.method == 'POST':
        form = TarefaNovaForm(request.POST)
        # Verificando se é valido e salvando
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tarefas:index'))
        else:
            tarefas_pendentes = Tarefa.objects.filter(feita=False).all()
            tarefas_feitas = Tarefa.objects.filter(feita=True).all()
            return render(
                request, 'tarefas/index.html', 
                {
                    'form': form, 
                    'tarefas_pendentes': tarefas_pendentes,
                    'tarefas_feitas': tarefas_feitas,
                }, 
                status=400
            )

    tarefas_pendentes = Tarefa.objects.filter(feita=False).all()
    tarefas_feitas = Tarefa.objects.filter(feita=True).all()
    return render(
        request, 'tarefas/index.html', 
        {
            'tarefas_pendentes': tarefas_pendentes,
            'tarefas_feitas': tarefas_feitas,
        }
    )


def detalhe(request, tarefa_id):
    if request.method == 'POST':
        tarefa = Tarefa.objects.get(id=tarefa_id)
        form = TarefaForm(request.POST, instance=tarefa)
        if form.is_valid():
            form.save()

    return HttpResponseRedirect(reverse('tarefas:index'))


def apagar(request, tarefa_id):
    if request.method == 'POST':
        Tarefa.objects.filter(id=tarefa_id).delete()
    return HttpResponseRedirect(reverse('tarefas:index'))

tarefas/templates/tarefas/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de tarefas</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
</head>
<body>
    <div class="container">
        <div class="row">
            <h1 class="mt-7 text-center">Lista de Tarefas</h1>

            <form action="{% url 'tarefas:index' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Descreva sua tarefa" aria-label="Descreva sua tarefa" aria-describedby="button-addon2" name="nome">
                    <button type="submit" class="btn btn-primary" id="button-addon2">Salvar</button>
                </div>
                <small class="form-text text_muted">{{ form.nome.errors }}</small>
            </form>

            <div class="col-md-6">
                <h2 class="text-center">Tarefas Pendentes</h2>
                {% for tarefa in tarefas_pendentes %}
                <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Descreva sua tarefa" aria-label="Descreva sua tarefa" aria-describedby="button-addon2" name="nome" required="required" value=" {{ tarefa.nome }}">
                        <button type="submit" class="btn btn-success" id="button-addon2">Marcar como feita</button>
                        <input type="hidden" value="checked" name="feita">
                    </div>
                </form>
                {% endfor %}
            </div>
            <div class="col-md-6">
                <h2 class="mt-7 text-center">Tarefas Concluídas</h2>

                {% for tarefa in tarefas_feitas %}
                    <div class="row">
                        <div class="col-2">
                            <form action="{% url 'tarefas:apagar' tarefa_id=tarefa.id %}" method="post">
                                {% csrf_token %}
                                <div class="input-group mb-3">
                                    <button type="submit" class="btn btn-danger" id="button-addon2">Apagar</button>
                                </div>
                            </form>
                        </div>
                        <div class="col-10">
                            <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">
                                {% csrf_token %}
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder="Descreva sua tarefa" aria-label="Descreva sua tarefa" aria-describedby="button-addon2" name="nome" required="required" value=" {{ tarefa.nome }}">
                                    <button type="submit" class="btn btn-warning" id="button-addon2">Marcar como Pendente</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>